### PR TITLE
Deferred loading of language switcher in Gutenberg editor (Posts and Widgets) & get_the_excerpt filter

### PR DESCRIPTION
**Pull request by g4rf**
As in issue #14 described, the language switcher isn't always loaded due to a race condition. This PR solves the problem with a deferred loading.

In addition it corrects some CSS overflow problems, when the "Top Toolbar" ist activated.

As a last thing for this pull request I added a filter for get_the_excerpt, so that excerpts are also translated, see #52.

### CODE REVIEW

**Comment by Sanjeevsetu** [comment]
Hi @g4rf 

Thanks for the PR. We have reviewed it and have merged.

**Comment by RolandTi** [comment]
Hi !
Does the @g4rf PR will be available only in the PRO edition as the language switcher for Gutenberg is listed as an PRO option : http://wp-multilang.com/pricing/

**Comment by Sanjeevsetu** [comment]
Hi @RolandTi 

@g4rf PR is already in free version. We have two types of language switcher. 

1. For admin/author used while writing blogs in different languages which is free
2. For end user used while reading article in different languages which is also free but it is missing inside Gutenberg block. 

We are planning to add it inside Gutenberg block in coming updates and yet to decide whether it would be free or pro. We have removed it currently from pricing list page. You can check it again.

**Comment by RolandTi** [comment]
Hi, thanks for your explanation. Have a nice day.

**Pull request merged**
